package art.cipher581.tools.pixelart.ui;

import java.awt.Color;
import art.cipher581.tools.pixelart.core.Pixel;


public class PixelPanel extends javax.swing.JPanel {

    private Pixel pixel;
    

    public PixelPanel(String description) {
        super(); 

        initComponents();
        
        setPixel(new Pixel(0, 0, Color.WHITE));
        // setBorder(new LineBorder(Color.BLACK, 1));
        
        jLabelDesc.setText(description);
    }
    
    
    public void setPixel(Pixel pixel) {
        this.pixel = pixel;
        
        jLabelValueX.setText(String.valueOf(pixel.getX()));
        jLabelValueY.setText(String.valueOf(pixel.getY()));
        
        Color c = pixel.getColor();
        jLabelValueRGB.setText("red: " + c.getRed() + "; green: " + c.getGreen() + "; blue: " + c.getBlue());
        
        jPanelColor.setBackground(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelX = new javax.swing.JLabel();
        jLabelY = new javax.swing.JLabel();
        jLabelRGB = new javax.swing.JLabel();
        jPanelColor = new javax.swing.JPanel();
        jLabelValueX = new javax.swing.JLabel();
        jLabelValueY = new javax.swing.JLabel();
        jLabelValueRGB = new javax.swing.JLabel();
        jLabelDesc = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabelX.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelX.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabelX, gridBagConstraints);

        jLabelY.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelY.setText("Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabelY, gridBagConstraints);

        jLabelRGB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelRGB.setText("RGB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabelRGB, gridBagConstraints);

        jPanelColor.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanelColor.setLayout(new java.awt.GridLayout(1, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanelColor, gridBagConstraints);

        jLabelValueX.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelValueX.setText("X Value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabelValueX, gridBagConstraints);

        jLabelValueY.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelValueY.setText("Y Value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabelValueY, gridBagConstraints);

        jLabelValueRGB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelValueRGB.setText("RGB Value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabelValueRGB, gridBagConstraints);

        jLabelDesc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelDesc.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabelDesc, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelRGB;
    private javax.swing.JLabel jLabelValueRGB;
    private javax.swing.JLabel jLabelValueX;
    private javax.swing.JLabel jLabelValueY;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JPanel jPanelColor;
    // End of variables declaration//GEN-END:variables
}
